// <auto-generated />
namespace GeyikCafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migration_Reservation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_Reservation));
        
        string IMigrationMetadata.Id
        {
            get { return "202409100006166_migration_Reservation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
