// <auto-generated />
namespace GeyikCafe.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migration_Menu : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migration_Menu));
        
        string IMigrationMetadata.Id
        {
            get { return "202409092329453_migration_Menu"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
